sonar.projectKey=TaskPro-Frontend
sonar.projectName=TaskPro Frontend Project
sonar.host.url=http://127.0.0.1:9000
sonar.token=sqp_02aef1388100ed8a54ecd16c78fd18a69419029a
sonar.sources=src
sonar.exclusions=node_modules/**, build/**, dist/**
sonar.language=js
sonar.sourceEncoding=UTF-8